name: Deploy Strava‑Refresh Cron

on:
  push:
    branches:
      - dev
      - deploying-cron-on-k8
    paths:
      - 'stravaSync/**'
      - 'k8s/cron-refresh.yaml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.GHCR_PAT }}" \
            | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build & push cron image
        run: |
          docker build \
            -f Dockerfile.cron \
            --platform linux/amd64 \
            -t ghcr.io/blitcore-org/rrs/cron-refresh:latest \
            .
          docker push ghcr.io/blitcore-org/rrs/cron-refresh:latest

      - name: Set up kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_CONTENT }}" \
            | base64 --decode > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Deploy CronJob to Kubernetes
        run: |
          kubectl apply -f k8s/cron-refresh.yaml